language: go

go:
  - 1.12.5

install:
  - make deps
script:
  - travis_wait make coveralls
notifications:
  email: false
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
