name: Example Deployment
application: frontend-nginx-benefits-enrollment

disableConcurrentExecutions: true
keepQueuedPipelines: true
description: This pipeline deploys some sweet code

notifications:
  - address: "#launchpad"
    type: "slack"
    when:
      - pipeline.complete
      - pipeline.failed
    message:
      pipeline.complete: |
        The stage has completed!
      pipeline.failed: |
        The stage has failed!

parameters:
  - name: "random"
    description: "random description"
    required: true
    default: "hello-world"

triggers:
- webhook:
    source: "random-string"
    enabled: true
stages:
- account: int-k8s
  name: apply deploy & svc

- account: int-k8s
  name: "Deploy Manifests"
  deployEmbeddedManifests:
    files:
      - file: test-deployment.yml
      - file: test-configmap.yml
      - file: test-sa.yml
    configuratorFiles:
      - file: test-configurator2.yml
        env: superOps
      - file: test-configurator.yml
    containerOverrides:
      - name: hcm
        resources:
          requests:
            cpu: "80"
            memory: "100"

- account: ops-k8s
  name: "Deploy"
  deploy:
    groups:
      - manifestFile: test-deployment.yml

- account: ops-k8s
  name: "Scale Up"
  scaleManifest:
    namespace: "looker"
    kind: "deployment"
    name: "looker"
    replicas: 5
- account: ops-k8s
  name: "Delete INT"
  deleteEmbeddedManifest:
    file: test-deployment.yml
- name: "Trigger Jenkins Job"
  jenkins:
    job: "QA/job/stage/job/UI/job/SLI"
    parameters:                           # Optional, if excluded Jenkins will use default parameter values
      - key: BROWSER
        value: "chrome"
      - key: Environment
        value: "stage"
      - key: NPMSCRIPT
        value: test:sli
    # master: "namely-jenkins"              # Optional, defaults to "namely-jenkins"
    # completeOtherBranchesThenFail: false  # Optional, defaults to false
    # continuePipeline: true                # Optional, defaults to true
    # failPipeline: false                   # Optional, defaults to false
    # markUnstableAsSuccessful: false       # Optional, defaults to false
    # waitForCompletion: true               # Optional, defaults to true
- name: "Trigger Spinnaker Pipeline"
  spinnaker:
    application: "badges"
    pipeline: "2c4a14d9-2f25-4a2a-b2d6-c31e596bce19"
    parameters:                           # Optional, if excluded Jenkins will use default parameter values
      - key: badges_docker_image
        value: "img:1234"
      - key: file_data
        value: "data=has,date=now"
      - key: file_path
        value: rel/ative/path
      - key: service_name
        value: coolName
    # completeOtherBranchesThenFail: false  # Optional, defaults to false
    # continuePipeline: false                # Optional, defaults to false
    # failPipeline: true                   # Optional, defaults to true
    # markUnstableAsSuccessful: false       # Optional, defaults to false
    # waitForCompletion: true               # Optional, defaults to true