name: Example Deployment
application: example

disableConcurrentExecutions: true
keepQueuedPipelines: true
description: This pipeline deploys some sweet code

notifications:
  - address: "#launchpad"
    type: "slack"
    when:
      - pipeline.complete
      - pipeline.failed
    message:
      pipeline.complete: |
        The stage has completed!
      pipeline.failed: |
        The stage has failed!

parameters:
  - name: "random"
    description: "random description"
    required: true
    default: "hello-world"

triggers:
- webhook:
    source: "random-string"
    enabled: true
stages:
- account: ops-k8s
  name: "Deploy Manifests"
  deployEmbeddedManifests:
    files:
      - file: test-deployment.yml
      - file: test-configmap.yml
      - file: test-sa.yml
    configuratorFiles:
      - file: test-configurator2.yml
        env: superOps
      - file: test-configurator.yml
- account: ops-k8s
  name: "Scale Up"
  scaleManifest:
    namespace: "looker"
    kind: "deployment"
    name: "looker"
    replicas: 5
- account: ops-k8s
  name: "Delete INT"
  deleteEmbeddedManifest:
    file: test-deployment.yml
- name: "Trigger Jenkins Job"
  jenkins:
    job: "QA/job/stage/job/UI/job/SLI"
    parameters:                           # Optional, if excluded Jenkins will use default parameter values
      - key: BROWSER
        value: "chrome"
      - key: Environment
        value: "stage"
      - key: NPMSCRIPT
        value: test:sli
    # master: "namely-jenkins"              # Optional, defaults to "namely-jenkins"
    # completeOtherBranchesThenFail: false  # Optional, defaults to false
    # continuePipeline: true                # Optional, defaults to true
    # markUnstableAsSuccessful: false       # Optional, defaults to false
    # failPipeline: false                   # Optional, defaults to false
    # waitForCompletion: true               # Optional, defaults to true