name: Example Deployment
application: example     # should match application created in spinnaker
triggers:                # list of triggers (currently only jenkins is supported)
- jenkins:
    job: "Example/job/master"
    master: "jenkins"
    propertyFile: "build.properties"
stages:
- account: int-k8s
  name: "Migrate INT"
  refId: "1"
  runJob:
    manifestFile: test-deployment.yml
    container: # override default command defined in the manifest
      command:
        - bundle
        - exec
        - rake
        - db:migrate
  notifications:
    - address: "#launchpad"
      type: "slack"
      when:
        - stage.complete
        - stage.failed
      message:
        stage.complete: |
          The stage has completed!
        stage.failed: |
          The stage has failed!
- account: int-k8s
  name: "Deploy to INT"
  refId: "2"
  reliesOn:
    - "1"
  deploy:
    groups:
      - manifestFile: test-deployment.yml
        maxRemainingASGS: 2 # total amount of replica sets to keep around afterwards before deleting
        scaleDown: true
        stack: web # primarily for labeling purposes on the created resources
        strategy: redblack
        targetSize: 2 # this is the total amount of replicas for the deployment
        containerOverrides: {}
- account: int-k8s
  name: "Proceed to Staging?"
  refId: "3"
  reliesOn:
    - "2"
  manualJudgement:
    failPipeline: true
    instructions: |
      If this stage has completed QA, press proceed.
