apiVersion: v1
kind: Pod
metadata:
  name: constraintpod
  namespace: scoopdewhoop
  labels:
    hello: world
spec:
  containers:
  - name: sise
    image: mhausenblas/simpleservice:0.5.0
    ports:
    - containerPort: 9876
    resources:
      limits:
        memory: "64Mi"
        cpu: "500m"
