name: Example Deployment
application: example

disableConcurrentExecutions: true
keepQueuedPipelines: true
description: This pipeline deploys some sweet code

notifications:
  - address: "#launchpad"
    type: "slack"
    when:
      - pipeline.complete
      - pipeline.failed
    message:
      pipeline.complete: |
        The stage has completed!
      pipeline.failed: |
        The stage has failed!

parameters:
  - name: "random"
    description: "random description"
    required: true
    default: "hello-world"

triggers:
- webhook:
    source: "random-string"
    enabled: true
stages:
- account: ops-k8s
  name: "Migrate INT"
  deployEmbeddedManifests:
    files:
      - file: test-deployment.yml
      - file: test-configmap.yml
- account: ops-k8s
  name: "Scale Up"
  scaleManifest:
    namespace: "looker"
    kind: "deployment"
    name: "looker"
    replicas: 5
- account: ops-k8s
  name: "Delete INT"
  deleteEmbeddedManifest:
    file: test-deployment.yml
